name: lelia
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_storage: ^2.1.1
  geolocator: ^13.0.1
  flutter_osm_plugin: ^1.3.0
  jiffy: ^6.3.1
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  image_picker: ^1.1.2
  path: ^1.9.0
  path_provider: ^2.1.4
  dotted_border: ^2.1.0
  photo_view: ^0.15.0
  permission_handler: ^11.3.1
  otp_text_field: ^1.1.3
  timer_count_down: ^2.2.2
  http: ^1.2.2
  dropdown_search: ^6.0.1
  flutter_spinkit: ^5.2.1
  excel: ^4.0.6
  flutter_image_compress: ^2.3.0
  image: ^4.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true


  assets:
    - assets/images/
  fonts:
    - family: Alexandria
      fonts:
        - asset: assets/fonts/Alexandria-VariableFont_wght.ttf




